### ISSUE TITLE
ForceCode hangs VS Code on startup

### ISSUE THREAD

**Issue by julesx** [daishi4u/ForceCode#54]
![image](https://user-images.githubusercontent.com/3010047/44533833-5e423c00-a6c4-11e8-9b50-ce835b30b7bf.png)

i ran into this when changing the org my ForceCode was logged into.

firstly, if you log out of an org, begin the login process, but then escape out, there are some error popups.

after logging in, my vs code locked up with a ton of popups about files that had changed on the new org

after restarting vs code, it just hangs trying to iterate through the giant task list.

i manually deleted the wsMembers.json file from my project workspace folder and then vs code and forcecode starts up no problem.  perhaps this deletion should be automatic when changing orgs?

**Comment by daishi4u** [comment]
OK so I see exactly what you're saying and that's a good point. I may need to do away with checking on startup anyways because the next piece I plan on working on is multi org login and that will conflict with that file.. My idea is to add an option in the force.json to allow multiple user names to be stored and then I will have a new view (like the code coverage view and running tasks view) with that list of usernames displayed. When you click one it will automatically switch and you'll be logged into both without needing to log out, but the one you click on will become the one that saves and everything work from... you'll see, it's gonna be great 😀

**Comment by julesx** [comment]
sounds great can't wait

**Comment by daishi4u** [comment]
This is now fixed, version 3.8.0 is uploaded. Please read the README as a LOT has changed including the project structure.
