### ISSUE TITLE
Step by Step instruction how to use Deploy Package

### ISSUE THREAD

**Issue by hubwozniak** [daishi4u/ForceCode#57]
Hi,

I would like to start using Deploy Package in ForceCode, but I have no idea what (e.g. files, org connections) I should prepare before to make everything work. Can someone share with me step by step instuction how  to use this feature ?

**Comment by daishi4u** [comment]
I would start by reading up on Salesforce package.xml stuff by going here: https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/manifest_samples.htm You can also get examples by setting overwritePackageXML to true in force.json then opening a file or files. When it comes time to create your own then make sure you set the overwritePackageXML back to false so that your package.xml doesn't get overwritten and once you're done creating it then do a deploy package from the menu and select the package.xml option.

**Comment by hubwozniak** [comment]
It is located in src folder. I tried prepering it myself and use generated by setting overwritePackageXML true, and does not work neither :/

**Comment by daishi4u** [comment]
Ok, so you need to only have the classes that you want to deploy in the source folder. If there are any extras that aren't in your package.xml then you will get errors. Another thing you will need to do is add the option "singlePackage": true in force.json. After that you will be able to deploy. I will be adding this option by default in the next release internally, but it can always be disabled by setting it to false, but then you need a package.xml for each file if you set it to false.

**Comment by daishi4u** [comment]
Looks like there is a bug with it though. It will be fixed in 3.8.0

**Comment by daishi4u** [comment]
This is now fixed, version 3.8.0 is uploaded. Please read the README as a LOT has changed including the project structure.
