### ISSUE TITLE
No definition found

### ISSUE THREAD

**Issue by hubwozniak** [daishi4u/ForceCode#83]
Hi,
I retreived all classes from my org, and tried to use  Go to Definition. When I click on something like: ClassName.MethodName, there is a pop up "No definition found for MethodName". I have already done Code Completion Refresh. Should i enable something more before using "Go to Definition"?

**Comment by hubwozniak** [comment]
Class from which method comes from is public.

**Comment by daishi4u** [comment]
If you have everything set up according to the salesforce apex extension then it would be an issue on their end. Make sure you have the cli and Java installed and configured in your vscode settings. I have no control over the go to definition as its not in the forcecode extension. Thanks.

**Comment by hubwozniak** [comment]
It works strange, when I copy all .cls files into 
\.forceCode\username\.sfdx\tools\sobjects\customObjects autocomplite works fine, but Go To Definition leads me to the file located in customObjects folder. E.g. System.Debug autocomplete also works fine. Autocomplete fails only when the class is located in the src folder. Any tips ?

**Comment by daishi4u** [comment]
You can always try and delete the apex.db file that is located in the .sfdx folder and then close and reopen vscode and see if the salesforce extension recreates this file. If not then something is wrong with your setup of the salesforce extension. When I had this problem it was because I didn't have the cli installed. Try that and let me know.
